[package]
name = "siren"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["__rustls", "__tls", "blocking", "brotli"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
